disabled_rules:
- nesting
- function_parameter_count

opt_in_rules:
- control_statement
- empty_count
- trailing_newline

excluded: 
- Carthage
- LoremPicsumApp/NeedleDI/NeedleGenerated.swift   
- LoremPicsumApp/NeedleGenerated.swift
- LoremPicsumApp/App

force_cast: warning

force_try: warning

type_body_length:
- warning: 300
- error: 400

file_length:
- warning: 500
- error: 800

large_tuple:
- warning: 3
- error: 4

type_name:
- min_length: 
- warning: 4
- error: 0

- max_length:
- warning: 30
- error: 35

