//
//  RandomImageInteractor.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Combine
import UIKit

protocol RandomImageBusinessLogic {
    func makeRequest(request: RandomImage.Request)
}

protocol RandomImageDataStore {
    // var name: String { get set }
}

class RandomImageInteractor: RandomImageBusinessLogic, RandomImageDataStore {
    // MARK: Public Properties

    var presenter: RandomImagePresentationLogic?

    // MARK: Private Properties

    private let fetcher: FetchingProtocol
    private var observer: AnyCancellable?

    // MARK: Initializers

    init(fetcher: FetchingProtocol) {
        self.fetcher = fetcher
    }

    // MARK: Public Methods

    func makeRequest(request: RandomImage.Request) {
        switch request {
        case .loadRandomImage:
            fetcher.fetchRandomImageData { result in
                switch result {
                case .success(let success):
                    self.presenter?.present(response: .presentRandomImageFrom(data: success))
                case .failure(let failure):
                    self.presenter?.present(response: .presentError(error: failure))
                }
            }
        }
    }
}
