//
//  RandomImagePresenter.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RandomImagePresentationLogic {
    func present(response: RandomImage.Response)
}

final class RandomImagePresenter: RandomImagePresentationLogic {
    // MARK: Public Properties

    weak var viewController: RandomImageDisplayLogic?

    // MARK: Public Methods

    func present(response: RandomImage.Response) {
        switch response {
        case .presentRandomImageFrom(let data):
            if let image = UIImage(data: data) {
                viewController?.display(viewModel: .displayRandom(image: image))
            }
        case .presentError(let error):
            if let error = error as? APIError {
                viewController?.display(viewModel: .display(error: error.rawValue))
            }
        }
    }
}
