//
//  GalleryRouter.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GalleryRoutingLogic {
    // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol GalleryDataPassing {
    var dataStore: GalleryDataStore? { get }
}

class GalleryRouter: NSObject, GalleryRoutingLogic, GalleryDataPassing {
    weak var viewController: GalleryViewController?
    var dataStore: GalleryDataStore?

// MARK: Routing (navigating to other screens)

// func routeToSomewhere(segue: UIStoryboardSegue?) {
//    if let segue = segue {
//        let destinationVC = segue.destination as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        let destinationVC = storyboard.instantiateViewController(
// withIdentifier: "SomewhereViewController") as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
// }

// MARK: Navigation to other screen

// func navigateToSomewhere(source: GalleryViewController, destination: SomewhereViewController) {
//    source.show(destination, sender: nil)
// }

// MARK: Passing data to other screen

//    func passDataToSomewhere(source: GalleryDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
