//
//  GalleryInteractor.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryBusinessLogic {
    func doSomething(request: Gallery.Something.Request)
//    func doSomethingElse(request: Gallery.SomethingElse.Request)
}

protocol GalleryDataStore {
    //var name: String { get set }
}

class GalleryInteractor: GalleryBusinessLogic, GalleryDataStore {
    var presenter: GalleryPresentationLogic?
    var worker: GalleryWorker?
    //var name: String = ""

    // MARK: Do something (and send response to GalleryPresenter)

    func doSomething(request: Gallery.Something.Request) {
        worker = GalleryWorker()
        worker?.doSomeWork()

        let response = Gallery.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Gallery.SomethingElse.Request) {
//        worker = GalleryWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Gallery.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
