//
//  MainInteractor.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func makeRequest(request: Main.Request)
}

protocol MainDataStore {}

final class MainInteractor: MainBusinessLogic, MainDataStore {
    // MARK: Public properties

    var presenter: MainPresentationLogic?

    // MARK: Private properties

    private let fetcher: FetchingProtocol

    // MARK: Initializers

    init(fetcher: FetchingProtocol) {
        self.fetcher = fetcher
    }

    // MARK: Public methods

    func makeRequest(request: Main.Request) {
        switch request {
        case .loadBackgroundImage:
            Task {
                do {
                    let data = try await fetcher.fetchRandomImage()
                    presenter?.present(response: .presentBackgroundImage(data: data))
                } catch {
                    presenter?.present(response: .presentError(error: error))
                }
            }
        }
    }
}
