//
//  GalleryPresenter.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryPresentationLogic {
    func present(response: Gallery.Response)
}

class GalleryPresenter: GalleryPresentationLogic {
    // MARK: - Public Properties

    weak var viewController: GalleryDisplayLogic?

    // MARK: - Public Methods

    func present(response: Gallery.Response) {
        switch response {
        case .presentPhotos(let photos):
            let photoViewModels = photos.map { PhotoViewModel(author: $0.author,
                                                              url: URL(string: $0.url),
                                                              downloadUrl: $0.downloadUrl,
                                                              size: "\($0.width) x \($0.height)",
                                                              previewUrl: $0.previewUrl)}
            viewController?.display(viewModel: .displayPhotos(photos: photoViewModels))
        case .presentError(let error):
            viewController?.display(viewModel: .display(error: error.localizedDescription))
        }
    }
}
