//
//  GalleryInteractor.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryBusinessLogic {
    func make(request: Gallery.Request)
}

protocol GalleryDataStore {
    var photos: [Photo] { get }
}

class GalleryInteractor: GalleryBusinessLogic, GalleryDataStore {

    var photos: [Photo] = []

    var presenter: GalleryPresentationLogic?
    var worker: GalleryWorker?

    private let fetcher: FetchingProtocol

    init(fetcher: FetchingProtocol) {
        self.fetcher = fetcher
    }

    func make(request: Gallery.Request) {
        switch request {
        case .fetchPhotos(let page, let perPage):
            Task {
                do {
                    photos = try await fetcher.fetchPhotos(page: page, limit: perPage)
                    presenter?.present(response: .presentPhotos(photos: photos))
                } catch let error {
                    presenter?.present(response: .presentError(error: error))
                }
            }
        }
    }
}
