//
//  GalleryInteractor.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryBusinessLogic {
    func fetchPhotos(page: Int?, perpage: Int?)
}

protocol GalleryDataStore {
}

class GalleryInteractor: GalleryBusinessLogic, GalleryDataStore {

    var presenter: GalleryPresentationLogic?
    var worker: GalleryWorker?

    private let fetcher: FetchingProtocol

    init(fetcher: FetchingProtocol) {
        self.fetcher = fetcher
    }
    func fetchPhotos(page: Int? = nil, perpage: Int? = nil) {
        Task {
            do {
                let photos = try await fetcher.fetchPhotos(page: page, limit: perpage)
                presenter?.present(photos: photos)
            } catch let error {
                presenter?.present(error: error)
            }
        }
    }
}
