//
//  GalleryRouter.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GalleryRoutingLogic {
    func routeToDetailsVC()
}

protocol GalleryDataPassing {
    var dataStore: GalleryDataStore? { get }
}

class GalleryRouter: NSObject, GalleryRoutingLogic, GalleryDataPassing {
    weak var viewController: GalleryViewController?
    var dataStore: GalleryDataStore?

    func routeToDetailsVC() {
        guard
            let source = viewController,
            let destination = source.photoDetailsBuilder?.photoDetailsViewController,
            var destinationDS = destination.router?.dataStore,
            let dataStore
        else {
            return
        }
        passDataToPhotoDetailsVC(source: dataStore, destination: &destinationDS)
        navigateToVC(source: source, destination: destination)

    }

    private func navigateToVC(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }

    private func passDataToPhotoDetailsVC(source: GalleryDataStore, destination: inout PhotoDetailsDataStore) {
        let indexPaths = viewController?.collectionView.indexPathsForSelectedItems
        if let indexPath = indexPaths?.first {
            destination.photo = source.photos[indexPath.item]
            guard let cell = viewController?.collectionView.cellForItem(at: indexPath) as? PhotoCell else { return }
            guard let image = cell.imageView.image else { return }
            destination.previewImage = image
        }
    }
}
