//
//  FavoritesModels.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 22.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Favorites {
    // MARK: Use cases

    enum Something {
        struct Request {

        }

        struct Response {

        }

        struct ViewModel {

        }
    }

//    enum SomethingElse
//    {
//        struct Request
//        {
//
//        }
//
//        struct Response
//        {
//
//        }
//
//        struct ViewModel
//        {
//
//        }
//    }
}
