//
//  FavoritesPresenter.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 22.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesPresentationLogic {
    func presentSomething(response: Favorites.Something.Response)
}

class FavoritesPresenter: FavoritesPresentationLogic {
    weak var viewController: FavoritesDisplayLogic?

    // MARK: Parse and calc respnse from FavoritesInteractor and send simple view model
    // to FavoritesViewController to be displayed

    func presentSomething(response: Favorites.Something.Response) {
        let viewModel = Favorites.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: Favorites.SomethingElse.Response) {
//        let viewModel = Favorites.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
