//
//  FavoritesViewController.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 22.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftUI

protocol FavoritesDisplayLogic: AnyObject {
    func displaySomething(viewModel: Favorites.Something.ViewModel)
//    func displaySomethingElse(viewModel: Favorites.SomethingElse.ViewModel)
}

class FavoritesViewController: UIViewController, FavoritesDisplayLogic {
    var interactor: FavoritesBusinessLogic?
    var router: (NSObjectProtocol & FavoritesRoutingLogic & FavoritesDataPassing)?
    var delegate: UITextFieldDelegate!

    private lazy var textField: UITextField = {
        let field = UITextField(frame: CGRect(x: 10, y: 100, width: 100, height: 40))
        field.backgroundColor = .white
        field.addTarget(self, action: #selector(textFieldDidChange), for: .editingChanged)
        return field
    }()

    private lazy var button: UIButton = {
        let button = UIButton(frame: CGRect(x: 100, y: 100, width: 200, height: 100))
        button.setTitle("TAP ME!", for: .normal)
        button.setTitle("Look but don't touch!", for: .disabled)
        button.setTitleColor(.white, for: .normal)
        button.setTitleColor(.gray, for: .disabled)
        button.isEnabled = false
        return button
    }()

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup Clean Code Design Pattern 

    private func setup() {
        let viewController = self
        let interactor = FavoritesInteractor()
        let presenter = FavoritesPresenter()
        let router = FavoritesRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: - Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
        view.backgroundColor = .orange
        view.addSubview(textField)
        view.addSubview(button)
//        doSomethingElse()
    }

    @objc private func textFieldDidChange(_ textField: UITextField) {
        button.isEnabled = {
            textField.text != ""
        }()
    }

    // MARK: - receive events from UI

    // @IBOutlet weak var nameTextField: UITextField!
//
//    @IBAction func someButtonTapped(_ sender: Any) {
//
//    }
//
//    @IBAction func otherButtonTapped(_ sender: Any) {
//
//    }

    // MARK: - request data from FavoritesInteractor

    func doSomething() {
        let request = Favorites.Something.Request()
        interactor?.doSomething(request: request)
    }
//
//    func doSomethingElse() {
//        let request = Favorites.SomethingElse.Request()
//        interactor?.doSomethingElse(request: request)
//    }

    // MARK: - display view model from FavoritesPresenter

    func displaySomething(viewModel: Favorites.Something.ViewModel) {
        // nameTextField.text = viewModel.name
    }
//
//    func displaySomethingElse(viewModel: Favorites.SomethingElse.ViewModel) {
//        // do sometingElse with viewModel
//    }
}

// MARK: Preview

struct FavoritesVC_Previews: PreviewProvider {
    static var previews: some View {
        FavoritesViewController()
            .makePreview()
    }
}
