//
//  PhotoDetailsInteractor.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 03.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDetailsBusinessLogic {
    func make(request: PhotoDetails.Request)
}

protocol PhotoDetailsDataStore {
    var photo: Photo? { get set }
    var previewImage: UIImage? { get set }
}

class PhotoDetailsInteractor: PhotoDetailsBusinessLogic, PhotoDetailsDataStore {

    var photo: Photo?
    var previewImage: UIImage?

    var presenter: PhotoDetailsPresentationLogic?

    func make(request: PhotoDetails.Request) {
        switch request {
        case .viewDidLoad:
            guard let photo, let previewImage else { return }
            presenter?.present(response: .presentPhoto(photo: photo))
            presenter?.present(response: .presentPreview(previewImage: previewImage))
        }
    }
}
