//
//  PhotoDetailsRouter.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 03.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhotoDetailsRoutingLogic {
    func presentSafariView(with url: URL?)
}

protocol PhotoDetailsDataPassing {
    var dataStore: PhotoDetailsDataStore? { get }
}

class PhotoDetailsRouter: NSObject, PhotoDetailsRoutingLogic, PhotoDetailsDataPassing {
    weak var viewController: PhotoDetailsViewController?
    var dataStore: PhotoDetailsDataStore?

// MARK: Routing (navigating to other screens)

    func presentSafariView(with url: URL?) {
        guard let source = viewController else { return }
        let destination = SafariView(url: url)
        present(source: source, destination: destination, presentationStyle: .formSheet)

    }

    private func present(source: UIViewController,
                         destination: UIViewController,
                         presentationStyle: UIModalPresentationStyle = .fullScreen) {
        destination.modalPresentationStyle = presentationStyle
        source.present(destination, animated: true)
    }
}
