//
//  MainViewController.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SnapKit
import SwiftUI
import UIKit

protocol MainDisplayLogic: AnyObject {
    func display(viewModel: Main.ViewModel)
}

class MainViewController: UIViewController {
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
    
    let randomImageBuilder: RandomImageBuilder?
    let galleryBuilder: GalleryBuilder?
    
    let fetcher: NetworkFetcher
    
    private var buttonOffset = UIScreen.main.bounds.maxY
    
    // MARK: Views
    
    private var imageView: UIImageView = {
        let view = UIImageView()
        view.contentMode = .scaleAspectFill
        let blurEffect = UIBlurEffect(style: .systemMaterialDark)
        let blurredView = UIVisualEffectView(effect: blurEffect)
        blurredView.frame = view.bounds
        blurredView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        blurredView.alpha = 0.8
        view.addSubview(blurredView)
        view.alpha = 0
        return view
    }()
    
    private var loadingIndicator: UIActivityIndicatorView = {
        let indicator = UIActivityIndicatorView(style: .large)
        indicator.hidesWhenStopped = true
        indicator.startAnimating()
        indicator.color = #colorLiteral(red: 0.1411764771, green: 0.3960784376, blue: 0.5647059083, alpha: 1)
        return indicator
    }()
    
    private lazy var randomButton: UIButton = {
        let button = UIButton()
        button.layer.cornerRadius = 12
        button.backgroundColor = .red
        button.setTitle("Show Random Image", for: .normal)
        button.titleLabel?.font = .boldSystemFont(ofSize: 20)
        button.titleLabel?.layer.shadowColor = UIColor.black.cgColor
        button.titleLabel?.layer.shadowOffset = CGSize(width: 0, height: 2)
        button.titleLabel?.layer.shadowRadius = 5
        button.titleLabel?.layer.shadowOpacity = 0.5
        button.layer.shadowColor = UIColor.red.cgColor
        button.layer.shadowRadius = 5
        button.layer.shadowOffset = CGSize(width: 0, height: 4)
        button.layer.shadowOpacity = 0.5
        button.layer.shouldRasterize = true
        button.layer.rasterizationScale = UIScreen.main.scale
        button.addTarget(self, action: #selector(showRandomVC), for: .touchUpInside)
        return button
    }()
    
    private lazy var galleryButton: UIButton = {
        let button = UIButton(type: .custom)
        button.layer.cornerRadius = 12
        button.backgroundColor = .blue
        button.setTitle("Show Gallery", for: .normal)
        button.titleLabel?.font = UIFont.boldSystemFont(ofSize: 20)
        button.titleLabel?.layer.shadowColor = UIColor.black.cgColor
        button.titleLabel?.layer.shadowOffset = CGSize(width: 0, height: 2)
        button.titleLabel?.layer.shadowRadius = 5
        button.titleLabel?.layer.shadowOpacity = 0.5
        button.layer.shadowColor = UIColor.blue.cgColor
        button.layer.shadowRadius = 5
        button.layer.shadowOffset = CGSize(width: 0, height: 4)
        button.layer.shadowOpacity = 0.5
        button.layer.shouldRasterize = true
        button.layer.rasterizationScale = UIScreen.main.scale
        button.addTarget(self, action: #selector(showGalleryVC), for: .touchUpInside)
        return button
    }()

    // MARK: Object lifecycle

    init(fetcher: NetworkFetcher, randomImageBuilder: RandomImageBuilder?, galleryBuilder: GalleryBuilder?) {
        self.fetcher = fetcher
        self.randomImageBuilder = randomImageBuilder
        self.galleryBuilder = galleryBuilder
        super.init(nibName: nil, bundle: nil)
        setup()
    }
    
    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: - Setup Clean Code Design Pattern

    private func setup() {
        let viewController = self
        let interactor = MainInteractor(fetcher: fetcher)
        let presenter = MainPresenter()
        let router = MainRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setupConstaints() {
        view.addSubview(imageView)
        view.addSubview(loadingIndicator)
        view.addSubview(randomButton)
        view.addSubview(galleryButton)
        let maxYOffset = UIScreen.main.bounds.midY + 50
        
        imageView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }
        
        loadingIndicator.snp.makeConstraints { make in
            make.centerX.equalToSuperview()
            make.bottom.equalToSuperview().inset(30)
        }
        
        randomButton.snp.makeConstraints { make in
            make.centerX.equalToSuperview()
            make.centerY.equalToSuperview().offset(maxYOffset)
            make.width.equalToSuperview().inset(40)
            make.height.equalTo(40)
        }
        
        galleryButton.snp.makeConstraints { make in
            make.centerX.equalToSuperview()
            make.centerY.equalToSuperview().offset(maxYOffset)
            make.width.equalToSuperview().inset(40)
            make.height.equalTo(40)
        }
    }
    
    private func setupNavigationBar() {
        // Make navigation bar invisible
        navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
        navigationController?.navigationBar.shadowImage = UIImage()
        navigationController?.navigationBar.isTranslucent = true
        navigationController?.view.backgroundColor = .clear
    }
    
    private func showButtons() {
        UIView.animate(withDuration: 1, delay: 0.25, usingSpringWithDamping: 0.7, initialSpringVelocity: 1) {
            self.galleryButton.snp.updateConstraints { make in
                make.centerY.equalToSuperview().offset(40)
            }
            self.randomButton.snp.updateConstraints { make in
                make.centerY.equalToSuperview().offset(-40)
            }
            self.view.layoutIfNeeded()
        }
    }
    
    private func animateImageView() {
        UIView.animate(withDuration: 0.8) {
            self.imageView.alpha = 1
        }
    }
    
    private func animateCorner() {
        CATransaction.begin()
        CATransaction.setAnimationDuration(3)
        CATransaction.setAnimationTimingFunction(CAMediaTimingFunction(name: CAMediaTimingFunctionName.easeInEaseOut))
        let animation = CABasicAnimation(keyPath: #keyPath(CALayer.cornerRadius))
        animation.fromValue = self.galleryButton.layer.cornerRadius
        animation.toValue = 30
        self.galleryButton.layer.cornerRadius = 30
        self.galleryButton.layer.add(animation, forKey: #keyPath(CALayer.cornerRadius))
        CATransaction.commit()
    }
    
    @objc private func showRandomVC() {
        router?.routeToRandomImageVC()
    }
    
    @objc private func showGalleryVC() {
        router?.routeToGalleryVC()
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupNavigationBar()
        setupConstaints()
        interactor?.makeRequest(request: .loadBackgroundImage)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        showButtons()
    }
}

struct MainViewController_Previews: PreviewProvider {
    static var previews: some View {
        MainViewController(fetcher: NetworkFetcher(networkService: NetworkService()), randomImageBuilder: nil, galleryBuilder: nil)
            .preview()
    }
}

extension MainViewController: MainDisplayLogic {
    func display(viewModel: Main.ViewModel) {
        switch viewModel {
        case .displayBackgroundImage(let image):
            DispatchQueue.main.async { [unowned self] in
                self.imageView.image = image
                self.loadingIndicator.stopAnimating()
                self.animateImageView()
            }
        case .displayError(let text):
            DispatchQueue.main.async { [unowned self] in
                self.showAlert("OPPS", "Something went wrong. Error: \(text)")
            }
        }
    }
}
