//
//  MainPresenter.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func present(response: Main.Response)
}

final class MainPresenter: MainPresentationLogic {

    // MARK: - Public Properties

    weak var viewController: MainDisplayLogic?

    // MARK: - Public methods

    func present(response: Main.Response) {
        switch response {
        case .presentBackgroundImage(let data):
            if let image = UIImage(data: data) {
                viewController?.display(viewModel: .displayBackgroundImage(image: image))
            }
        case .presentError(let error):
            guard let error = error as? APIError else { return }
            viewController?.display(viewModel: .displayError(text: error.rawValue))
        }
    }
}
