//
//  RandomImageInteractor.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RandomImageBusinessLogic {
    func doSomething(request: RandomImage.Something.Request)
//    func doSomethingElse(request: RandomImage.SomethingElse.Request)
}

protocol RandomImageDataStore {
    //var name: String { get set }
}

class RandomImageInteractor: RandomImageBusinessLogic, RandomImageDataStore {
    var presenter: RandomImagePresentationLogic?
    var worker: RandomImageWorker?
    //var name: String = ""

    // MARK: Do something (and send response to RandomImagePresenter)

    func doSomething(request: RandomImage.Something.Request) {
        worker = RandomImageWorker()
        worker?.doSomeWork()

        let response = RandomImage.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: RandomImage.SomethingElse.Request) {
//        worker = RandomImageWorker()
//        worker?.doSomeOtherWork()
//
//        let response = RandomImage.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
