//
//  RandomImageModels.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RandomImage {
    // MARK: Use cases

    enum Request {
        case loadRandomImage
    }

    enum Response {
        case presentRandomImageFrom(data: Data)
        case presentError(error: Error)
    }

    enum ViewModel {
        case displayRandom(image: UIImage)
        case display(error: String)
    }
}
