//
//  RandomImagePresenter.swift
//  LoremPicsumApp
//
//  Created by Aleksandr Kretov on 14.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RandomImagePresentationLogic {
    func presentSomething(response: RandomImage.Something.Response)
}

class RandomImagePresenter: RandomImagePresentationLogic {
    weak var viewController: RandomImageDisplayLogic?

    // MARK: Parse and calc respnse from RandomImageInteractor and send simple view model to RandomImageViewController to be displayed

    func presentSomething(response: RandomImage.Something.Response) {
        let viewModel = RandomImage.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: RandomImage.SomethingElse.Response) {
//        let viewModel = RandomImage.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
